### ISSUE TITLE
Update APBS and PDB2PQR to the latest version of Opal

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-pdb2pqr#103]
Opal Python Version 2.2 was released in 2010. This release corresponds to the latest release of the Opal Java core implementation. More info can be found at:

https://sourceforge.net/mailarchive/forum.php?forum_name=opaltoolkit-users&max_rows=100&style=nested&viewmonth=201002&viewday=12

We may need to update opal-py in contrib/, the current version of opal-py used is 1.9.3.

**Comment by kmonson** [comment]
The big thing holding this up was figuring out how to regenerate the AppService_* files. The needed input wsdl file is not in the repo. Turns out it can be found here: http://nbcr-222.ucsd.edu/opal2/services/pdb2pqr_2.0.0?wsdl

As a bonus that file also lists all of the interface methods for opal, something that was not easily discovered in the existing code.
