### ISSUE TITLE
protein-RNA results are AWOL since APBS 1.0.0

### ISSUE THREAD

**Issue by keith923** [Electrostatics/apbs-pdb2pqr#149]
The [README.html](https://github.com/Electrostatics/apbs-pdb2pqr/blob/7c0f57e0699e40bf92b2182deaf7889a35ea8ec7/apbs/examples/protein-rna/README.html) file has not been updated since 1.0.0.  The test is also not being run from the new-fangled Python-based testing script.

I do not know if this is in error, or if something changed.  If the latter turns out to be the case, perhaps we can move the example to a "historical" directory, under examples?

**Comment by keith923** [comment]
Peter's above comment comes from the work he did for the [tutorial](http://www.poissonboltzmann.org/examples/Protein-Rna_Tutorial/).

**Comment by kozlac** [comment]
If people follow Peter's tutorial, the downloads fail for the python script and shell script can't with the error that the server can't find the file. (e.g https://raw.githubusercontent.com/PEMIfolder/github.io-PEMIfolder/gh-pages/Tut_scripts_PR/apbs_unix_dx.py). All the scripts are displayed and they can be cut and pasted. However the instructions would have to be changed.

**Comment by kozlac** [comment]
Got the example to run. The issues are:
1) The scripts and bash download links are/were down  in the tutorial webpage. This is in issue #348.
2) The template.in file is missing write statements to print dx file that dxmath will use later.(Also, in the tutorial it ask to rename template.in to template.txt why don't we have it like this to begin with?).
3) Like pzli3 mentioned above the makefiles can't be run anymore. 
4) I had to manually add dxmath to my path. I am guessing this may be done at building time? Otherwise, it may be useful to comment you have to do it or show how to do it in the tutorial.

Do we want to create cmake files for this? Or how do you want to proceed @lizutah , @keith923 ?

**Comment by keith923** [comment]
This still needs to be integrated into the automated unit tests.

**Comment by keith923** [comment]
I've incorporated these tests into the test suite.  I think that we still need a README.md file in the directory to mirror what's in the other example directories.

**Comment by kozlac** [comment]
I can do the readme's unless you really, really, really want to do it.:)

**Comment by keith923** [comment]
That would be perfect!  Thanks @kozlac!

**Comment by kozlac** [comment]
Table is there. Will be updated as per issue #407. Closing issue.
