### ISSUE TITLE
add nightly builds for APBS

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#249]

**Comment by lizutah** [comment]
Progress: 
https://github.com/Electrostatics/apbs-pdb2pqr/blob/master/.travis.yml
https://travis-ci.org/Electrostatics/apbs-pdb2pqr

**Comment by keith923** [comment]
Travis CI will stop a job if it get's no output for 10 minutes.  On Linux, apbs-smol-parallel.in takes longer than 10 minutes.  On the OS X boxes it finished with 4 seconds to spare.  So the Linux tests won't run on Travis CI and the OS X tests may not always.

Additionally there is another time out that limits a single script to running for no more than 50 minutes.  The OS X jobs are still running, but they might bump up against that limit.

I'm considering some various workarounds now.  We can have the Python test script print a period every few seconds to get around the first problem.  For the second problem, we may need to have separate Python scripts for each test.  We may not.  It's possible that since the Python code is actually forking off jobs to run APBS, we may not bump into the 50 minute issue.  We'll just have to wait and see.

**Comment by keith923** [comment]
Just as I finished typing, Travis CI killed the test runner before it could finish.

**Comment by keith923** [comment]
This is working now.  Travis CI runs when master changes.  It builds on OS X and Linux, FETK ON/OFF, and runs all of the tests.

Ignoring any tweaks that we might want to make in the future -- some fancy reporting, like integrating the test results into a web page, or some such thing -- this is done.  We'll deal with tweaks later in other issues.
