### ISSUE TITLE
BEM - release in APBS

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#252]

**Comment by keith923** [comment]
Not sure what this means exactly.  The BEM code is in APBS already.  We don't enable it by default, nor do we build our binary releases with it enabled.  Part of the issue is that it relies on Fortran.  If we decide we want to enable this in our binary distribution, before we convert it to C/C++ (issue #251) then we'll need to investigate the implications of including the Fortran runtime libs.

**Comment by lizutah** [comment]
Needs to be in C/C++, compiled with APBS, to be "released."

**Comment by lwwilson1** [comment]
BEM/ TABI-PB compiles and runs as part of APBS on Mac OS X, Windows, and Linux.
