### ISSUE TITLE
add "write" parameter to Geometric Flow code

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#268]
We need to write out some data from geoflow.  See the "write" statement in http://www.poissonboltzmann.org/docs/apbs-overview/#elec.

@keith923 is working on outputting the dielectric map now

**Comment by keith923** [comment]
It looks like I'd already figured out what I had wanted to write.  I guess I just never got around to implementing it.  @kozlac there is a comment [here to output "surfu"](https://github.com/Electrostatics/geoflow_c/blob/e8ce510a670e0b7f3501e72be6141fc20328f947/src/GeometricFlow.cpp#L229), which IIRC represents the surface of the molecule.  I'm going to poke around in the code some more and see if I can reestablish a handle on what the code does.

@sobolevnrm do you have any requests for what should be available to save to a dx file?  I think that this is pertinent for Sphinx as well, because I think that we'll want to also make the same data available for pushing down the pipeline to downstream plugins.  @kozlac with that in mind see if you can't write the code in such a way as to not bind it too tightly to the retro APBS implementation.
