### ISSUE TITLE
document GUI problems for 3d mol on other web browsers

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#324]
3dmol works reasonable well in firefox.  We need to document (and later fix) bugs in other browsers.

**Comment by mchun0630** [comment]
None of the browsers I tested (Firefox, Opera, IE, Chrome) are completely “bug free”, as in the browsers never have any issues in all the trials I’ve done so far. But some are less prone to bugs than others. 
In general, the opaque button doesn’t work unless you switch the button back and forth instead of on the first try. I’m not sure if this is intentional, but it works that way. The show/hide buttons also have a bit of a glitch in which the white square on the buttons highlights blue, and then moves jaggedly to show “hide”
I’ve also noticed that different trials with different browsers had different bugs; there were no real “consistent” bugs in the browsers per say, but a group of bugs (for example, going extreme values and trying to reset didn’t work, switching between color scheme was laggy or rendered the wrong color scheme) were present or not present in all the browsers, depending on the trial at hand. All browsers had no problems with model type though. All browsers also have a problem where electrostatic potential maps correctly with SAS, but VDW and SES have the patchy, incorrect emulation, and a problem when you reset values the sliders don’t return back to normal.  
Usually refreshing cleared some big problems, like incorrect representation of color scheme, but sometimes it just cleared the “current” problems but made new ones.

**Comment by mchun0630** [comment]
Opera: The range sliders seem to work, but the translucent/ opaque button sometimes seems to be broken. Also, the Surface type, color schema seem to not work, or are extremely laggy. Sometimes though, 3Dmol starts off with the wrong color scheme.

**Comment by mchun0630** [comment]
Firefox: Is a bit laggier when it comes to the range sliders going to extreme values. And if you switch between transparent and opaque too many times, the electrostatic visualization lags and disappears and leaves you with just the molecule until its caught up again. Other than that all the functions seems to work properly (except for the general bug thing).

**Comment by mchun0630** [comment]
Chrome: Seems to work fine in Chrome. However, the general problems of sometimes unstable range sliders are still and issue. But chrome does seem to be the least buggy (at least in my experience)

**Comment by mchun0630** [comment]
Internet: The functions seem to work, but the buttons seem to be very slow. The coloring seems to be off in that if you toggle between different colors, colors from different schemas seem to blend in with one another.

**Comment by mchun0630** [comment]
Safari: In older versions of safari, it seems the GL viewer doesn’t work (5.1). In the newest version of safari (8), the viewer does work. Safari sometimes freezes if you toggle with the interface too much. Other than that, it has the normal bugs, but isn’t particularly more buggy in comparison to the other browsers.

**Comment by karinaliles** [comment]
everything works fine for Opera and Chrome. Firefox is still slow. I'm working on trying to figure out why. The IE range sliders don't work. Thats documented in a new issue #389. I can't test for safari. The viewer does not load. I'm not sure if it is because I'm using a PC. If someone could check that'd be great. I'm opening a new issue for Safari and closing this issue.
