### ISSUE TITLE
Evaluate current APBS GPU implementation

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#338]
and investigate NVIDIA library (cuSOLVER).

**Comment by kozlac** [comment]
@sobolevnrm Is this what you meant:

I am using [1FAS.in.txt](https://github.com/Electrostatics/apbs-pdb2pqr/files/40524/1FAS.in.txt) and [1FAS.pqr.txt](https://github.com/Electrostatics/apbs-pdb2pqr/files/40525/1FAS.pqr.txt) as the base molecule to do all the testing and benchmarking for the gpu code since this molecule has decent size. Some of the relevant parameters of the 1FAS.in file are:

1. method: mg-auto
2. usegpu
3. pde type: lpbe
4. bcfl: sdh
5. srfm: smol
6. chgm: spl2

In broad terms, the code I implemented reads the *usegpu* keyword from the .in file and uses the gpu to apply Weighted Jacobi smoothing as part of the multigrid method.

In order for the program to recognize and use the keyword *usegpu* I made following changes. 

In src/generic/mgparm.c I added the flag *useGpu* to the MGparm type. **MGparm_ctor2(..)** method sets this flag to zero by default (that is, do not use gpu). The .in file is read by the different parsing methods in nosh.c. Eventually the **MGparm_parseToken(...)** in src/generic/mgparm.c method is called and if the *usegpu* keyword was read the flag is updated to 1.

During the call to **initMG(...)**  in main.c a **Vpmgp** type is created in the **Vpmg_ctor2(...)** method in src/mg/vpmg.c. The **Vpmgp** type holds most of the information about the method to be used, grid sizes, grid center, number of iterations, etc.  Most of the **MGparm** information is also passed to the **Vpmgp** type. I also added a gpu field to the Vpmgp type and it is updated in the **Vpmgp_ctor2(..)** method with the value *mgparm->usegpu*.

Some important parameters that are also set in **Vpmgp_ctor2(..)** are:

1. errtol = 1.0e-6. This is the default value if the error tolerance is not specified in the .in file.
2. nu1 and nu2. This is the number of pre-smoothing and post-smoothing respectively. The default is 2 for both.
3. itmax = 200. Maximum number of iterations for the smoothing method.
4. mgsmoo. The smoothing method. The default is Gauss-Seidel. 

The **Vpmgp** type is then stored in a **Vpmg** type array whose size depends on the number of elec statement from the .in file.

**Vpmg_ctor2(...)** also calls the **Vpackmg(...)** method in src/pmgc/mgsubd.c. What **Vpackmg (...)** does is encode the different flags and parameters in one array *iparm*. The *gpu* flag is stored in **VAT(iparm,23) = iparm[22]**. 

**initMG(...)** returns in main.c after finishing setting up the MG parameters and then calls **solveMG(...)**. At this point all the information to solve the current calculation is stored in the *pmg* struct. 

In src/mg/vpmg.c the current pde's matrix and r.h.s are calculated and stored. and passed to the method driver to be used (e.g. CG, Newton, or MG). 

In /src/pmgc/mgdrvd.c **Vmgdriv2(...)** method the **pmgp** parameters are decoded. The multigrid structure is set up, the fine and coarse operators are filled,etc..  Eventually the smoothing method is called via:

(src/pmgc/mgcsd.c)**Vmvcs(...)** -> (src/pmgc/smoothd.c)**Vsmooth(...)** 

The only smoothing methods currently implemented are Gauss-Seidel or Conjugate Gradient methods. Right now I am using the flag for Gauss-Seidel to go into (src/pmgc/gsd.cu)**Vgsrb(...)**. 

The gpu flag is passes along to (src/pmgc/gsd.cu)**Vgsrb(...)**  where if set to 1 then the gpu code is used to perform the set number of Weighted Jacobi smoothing passes in the gpu's kernel. Currently the weight is set to 2/3. 

Some things to note:

1. I should change the smoothing code to the already coded wjac (Weighted Jacobi)
2. As is, right now there are no checks to make sure that the gpu code is supported or some heuristics to see if it should even be used.
3. The program is still using the multgrid method and not just solving in 1 level.
4. There is support to use more than one gpu and code could be implemented to solve more that one elec statement  in parallel if problem size is within gpus' capabilities.

I timed 20 calls to **solveMG(...)** using cpu code versus the gpu code with different number of threads per block and grid sizes. The average calling times (sec) are:

               |         |        |Gpu Threads | |
-------------|-------|-------|-------|-------|
Grid Size | Cpu | 256 | 384 | 512 |
65x65x65| 0.84| 3.20| 3.09| 3.14|
97x65x65| 1.64| 3.19| 3.22|  3.20|
97x97x65| 2.67| 3.75| 3.78| 3.80|
97x97x97| 2.58| 3.57| 3.62| 3.68|
129x97x97| 3.15| 3.83| 3.88| 3.80|
129x129x97| 4.99| 4.06| 4.07| 4.12|
129x129x129| 5.14| 4.45| 4.53| 4.52|
161x161x161| 10.44| 6.31| 6.25| 6.33|

The gpu average time increases at a lower rate than that of the cpu. Again, it is important to remember that I am comparing the average time of one call to the **solveMG(...)** where the cpu is using Gauss-Seidel smoothing whereas the gpu is using Weighted Jacobi which tends to be slower. I didn't implemented GS in the gpu kernel since the method uses updated values during the current update and that would cause threads to collide if ran in parallel. GS could be implemented with slight modifications.

**Comment by sobolevnrm** [comment]
Are all of the results in this table from the same code and same system?  Which system:  your desktop or Constance?

**Comment by kozlac** [comment]
I ran the gpu times in Constance and the CPU times that I sent were from my local computer. I did a couple of runs in Constance for the CPU but between the gpu and CPU waiting for resources I decided to take the ones from my computer since other than the video card it has good hardware.

--Juan Brandi

Sent from my Android phone using Symantec TouchDown (www.symantec.com)

-----Original Message-----

**Comment by sobolevnrm** [comment]
We need the timings from the same system in order to allow a fair
comparison.

**Comment by kozlac** [comment]
I ran the cpu code in Constance. Below are the cpu times compared to gpu code with 384 threads:

grid size | cpu | gpu w/384 threads
------------|-------|--------
65\*65\*65 | 0.23 | 3.09
97\*65\*65 | 0.4 | 3.22
97\*97\*65 | 0.83 | 3.78
97\*97\*97 | 1.13 | 3.62
129\*97\*97 | 1.53 | 3.88
129\*129\*97 | 2.56 | 4.07
129\*129\*129 | 2.51 | 4.53
161\*129\*129 | 3.47 | 5.08
161\*161\*129 | 5.08 | 5.66
161\*161\*161 | 5.35 | 6.25
193\*161\*161 | 6.6 | 6.95
193\*193\*161 | 9.51 | 8.17
193\*193\*193 | 9.10 | 8.34

[runTimes.docx](https://github.com/Electrostatics/apbs-pdb2pqr/files/49168/runTimes.docx)

It took a little bit longer but the gpu smoother version eventually does run faster. A question was raised by Keith that if we know that the nodes containing the gpu's are the same as the all the other nodes in Constance. By the specification in the [Cosntance page](https://confluence.pnnl.gov/confluence/display/PICHELP/Constance) is seems that they are all the same. I will try to find out for sure.
