### ISSUE TITLE
GPU Heuristics and Safeguards

### ISSUE THREAD

**Issue by kozlac** [Electrostatics/apbs-pdb2pqr#384]
Write some code to safeguard unknown or undesired calls from the .in file using the gpu. I have some ideas of what to look for but @sobolevnrm is there something that you can think of that we better look for?

**Comment by sobolevnrm** [comment]
Heuristics and safeguards are two different things -- can you split this issue into two:
* An enhancement issue for allowing APBS to decide when to use GPU acceleration (if available) as well as to switch between different types of solvers based on problem size.
* A critical issue safeguarding users by exploring the different code paths where GPUs could or could not be used and making sure that you handle exceptions arising from incompatible solvers, unavailable GPUs, etc.

**Comment by lizutah** [comment]
I think the second issue should be handled by cmake.

**Comment by keith923** [comment]
How exactly?  I can see how CMake could determine how to build for different GPU architectures, but how would it handle things are run time, which is what I think Nathan as thinking about.

**Comment by sobolevnrm** [comment]
Yes, I was thinking about runtime checks.

**Comment by sobolevnrm** [comment]
To be more specific:  we need to safeguard against calls to unimplemented
solvers -- in both the CPU and GPU versions of the code.  These should
happen both in runtime checks (e.g., for input file commands that aren't
feasible on current hardware or based on implemented features) as well as
in compile-time checks (I'm worried that there are too many dead-ends in
the code with solvers that have only been stubbed out rather than
implemented).

**Comment by kozlac** [comment]
I have created [issue #338 ](https://github.com/Electrostatics/apbs-pdb2pqr/issues/388) for the safeguards and lave this one for the GPU acceleration and heuristics.
