### ISSUE TITLE
Upgrade graphcut

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#411]
@sobolevnrm fixed the numerous and crazy bugs.  The code in https://github.com/Electrostatics/graphcut (python3) has major changes from the version in PDB2PQR.  We need to replace that version (and any others out there) as soon as possible.

**Comment by kmonson** [comment]
Fixed in 9608170290137bc80ed4bf7ac555bc3312c111b9. (Yes, I forgot to put the issue number in my commit message again. Sue me. :P)

In @sobolevnrm's fixed graphcut code it would output 3 curves for each HIS residue. I removed the two extra curves as they produce lots of warnings in PDB2PKA and are not used. Re-adding them is as simple as uncommenting two lines in titration_curve.py if desired.
