### ISSUE TITLE
bug while parsing parameter file?

### ISSUE THREAD

**Issue by jaredsagendorf** [Electrostatics/apbs-pdb2pqr#434]
I am trying to read in an AMBER parameter file using the `READ parm` statement. Attatched is my .pqr file, the parameter file, and the .in file.

When I run the .in file, I am getting the follow output with the error:

> This executable compiled on Jan  8 2016 at 17:11:27
> 
> Parsing input file 1ztgGbind.in...
> read
> Parsed input file.
> Reading parameter data from vparam-amber-parm94.dat.
> Got paths for 1 molecules
> 
> WARNING!!  Radius/charge information from PQR file 1ztg.pqr
> will be replaced with data from parameter file (vparam-amber-parm94.dat)!
> Reading PQR-format atom data from 1ztg.pqr.
> **Vparam_getAtomData:  unable to find atom 'P', res 'DC'
> Valist_readPDB:  Couldn't find parameters for atom = P, residue = DC
> Error reading molecules!**

However, the atom P is very clearly defined in the parameter file for residue DC. So what the hell? Note that this is just a minimal working example, I do need to read in this parameter file for my actual calculation. Some help figuring this out would be greatly appreciated... I hope it's something simple.

[MWEfiles.zip](https://github.com/Electrostatics/apbs-pdb2pqr/files/218127/MWEfiles.zip)

**Comment by kozlac** [comment]
Hello @jaredsagendorf, the problem is that the residue "DC" in the .dat file starts at line 698, ends at line 720, and continues at line 750 where the atom "P" is located. The parser sees the new residue name "DCN" and stops reading, that is why it can find it. A quick solution is to make sure that all lines with residues of the same name are contiguous. I moved the residues in the attachement [vparam-amber-parm94.dat.txt](https://github.com/Electrostatics/apbs-pdb2pqr/files/219649/vparam-amber-parm94.dat.txt] file and APBS completed successfully. Where did you get the .dat file?

I will look into a more permanent fix for the parser.
