### ISSUE TITLE
GAMer libraries OR headers missing ...EXITING ON ERROR

### ISSUE THREAD

**Issue by mvfbarrionuevo** [Electrostatics/apbs-pdb2pqr#437]
Hi,

I'm getting an error when trying to build fetk and I can't figure it out a way to work around this problem. Could someone help? Please.

Here is the error message I got:

---------- begin configuring for GAMER linkage ---------------
checking whether your environment defines FETK_INCLUDE... yes
checking whether your environment defines FETK_LIBRARY... yes
checking how to run the C++ preprocessor... g++ -E
checking gamer/gamer.h usability... no
checking gamer/gamer.h presence... no
checking for gamer/gamer.h... no
configure: error: GAMer libraries OR headers missing ...EXITING ON ERROR
make: *** No rule to make target 'install'.  Stop.
~/Data/Scripts/abps/apbs-pdb2pqr/apbs/linux/fetk
---------------------- FETK-BUILD: STOPPING ----------------------

**Comment by kozlac** [comment]
Hello @mvfbarrionuevo , the reason your build is failing is because the builder can't find the GAMer libraries. However these libraries are included with the APBS distribution in apbs/externals/fetk/gamer/src/aaa_inc/gamer/gamer.h, etc... Could you give us more details about where you got the source files, APBS version, and the command you are using to build it? Thanks!

**Comment by mvfbarrionuevo** [comment]
Hi there,

I'm sorry to bother you about it, but I figured it out and already solve 
the issue.

Thanks a lot.

Kind regards,

-- 
Manoel V.F. Barrionuevo
Master's student
State University of Campinas

**Comment by kozlac** [comment]
Glad to hear it!!

**Comment by matiasmartineza** [comment]
I know it's been a while, but I'm having the same issue and I don't know how to figure it out. Could you help me with this?

**Comment by matiasmartineza** [comment]
I have not installed APBS but I installed maloc. I get the same error when installing GAMer, but with maloc.h "checking maloc/maloc.h usability... no | checking maloc/maloc.h presence... no". I've been trying adding `--libdir=/home/matiasmartinez/Descargas/gamer/include`, because I have the maloc.h file in that directory, but it keeps throwing that same error.

**Comment by kozlac** [comment]
You should add the -I option to include any directories where the compiler should look for header files. E.g:
`gcc -I/path/to/my/header my_program.c -o MyProgram`
