### ISSUE TITLE
Windows binary at Sourceforge

### ISSUE THREAD

**Issue by thomas836** [Electrostatics/apbs-pdb2pqr#507]
Hi,

I tried to run the windows binary currently, however I noted, that APBS didn't use multithreading and only used 1 core out of 12 possibles of the CPU. Additionally, when I tried to run the parallel mg mode the program instantly crashed. This happened for the binaries of the 1.5, 1.4.1 and 1.4.2 build. The log file says, that the APBS version wasn't compiled with MPI in case for the mg-para.
Is was wondering if there is any fix for this.
Thanks a lot for your help.

Cheers

**Comment by kozlac** [comment]
Hello @fubula , we usually don't distribute the binaries with MPI support since not every system will have the necessary libraries or capabilities. For the multi-threading, that was on oversight. The compilation flag for multi-threading used to be enabled by default which changed at some point and we failed to noticed. I can create a binary with multi-thread support and let you know as soon as is up. However, if you need MPI I could try to help you walk through the steps for compiling a binary.

**Comment by sobolevnrm** [comment]
Hi @kozlac, please create the multi-thread support binary regardless.  Thanks!

**Comment by kozlac** [comment]
@fubula I'm hoping to have it by tonight or tomorrow.

**Comment by kozlac** [comment]
@fubula, the windows binary with thread support is up. Thank you for your patience.
