### ISSUE TITLE
Source code releases for APBS-1.5 are missing source code for external subdirectories

### ISSUE THREAD

**Issue by jwhowarth** [Electrostatics/apbs-pdb2pqr#508]
Both the zip and tar.gz source code release of APBS-1.5 are unbuildable because they were packaged without the contents of the external subdirectories. The apbs/externals/bem, apbs/externals/fetk, apbs/externals/geoflow_c, apbs/externals/mesh_routines and apbs/externals/pb_s_am subdirectories are all unpopulated.

**Comment by kozlac** [comment]
hello @jwhowarth are you downloading from the github repo or sourceforge. Also, are you downloading the source code or the binaries?

**Comment by jwhowarth** [comment]
The source archives from https://github.com/Electrostatics/apbs-pdb2pqr/releases both contain empty external subdirectories. There are no 1.5 source files on sourceforge.

**Comment by kozlac** [comment]
Hello @jwhowarth, since the source code is automatically generated by the github repository I reached to the github team (see below). In short, it is not currently possible to include the source code for submodules. Thus I see two possibilities, 1) Clone the repo and checkout the release tag and then do submodule init and update. 2) Within the current source code there's a gitsubmodule file with all the submodule dependencies. You could create an empty git in the root folder and then individually do git module add. Sorry for the inconvenience. 

>Hello, I was wondering if it is possible to include the source code of submodules along with the source code of the main project in a release? If not possible, is there a way to include the .git folder and not just the .gitignore and the .gitmodule files. So that it will possible to just make the calls for submodule init and update. Thanks!!
---
>Hi there,
Thanks for reaching out! That's not currently possible, but I would be happy to pass it along to the team as a feature request. I can't promise if or when it will be implemented, but your suggestion is definitely in the right hands!
Regards,
Laura
@lecoursen
GitHub Support
