### ISSUE TITLE
Error message that I have no idea how to fix

### ISSUE THREAD

**Issue by skigirl618** [Electrostatics/apbs-pdb2pqr#509]
I am trying to run a PQR file I made in pdb2pqr through apbs and I keep getting this error message:
Vcom_ctor2: process 0 of 1 is ALIVE!
Valist_readPQR:  Error parsing atom 4111!
Please double check this atom in the pqr file, e.g., make sure there are no concatenated fields.
Error reading molecules!

I am not good with code at all so I have no idea how to fix this or if it is an issue with the original PDB.

**Comment by kozlac** [comment]
Hello @skigirl618, it seems that the issue is in the pqr file that is being provided to APBS. You can open the pqr file with any text editor and go to atom 4111 and make sure that it follows the right format (i.e. compare it to the other atoms that are being read correctly. Most likely, one of the values has more significant digits and is running into the next one. You should be able to separate them by spaces. Also, please feel free to email me your pqr file (juan.brandi-lozano@pnnl.gov) and I could check it too.

**Comment by kozlac** [comment]
The problem was some of the (x, y, z) values for the ATOM records in the pqr file were concatenated, e.g.:

`ATOM   1234  AB  ABC   123      53.070  30.252-100.167 -0.0000 1.0000`

The solution is to make sure there is a space between them:

`ATOM   1234  AB  ABC   123      53.070  30.252 -100.167 -0.0000 1.0000`
