### ISSUE TITLE
extension .py.in import fails

### ISSUE THREAD

**Issue by mjag1898** [Electrostatics/apbs-pdb2pqr#519]
my python installation (2.7 through miniconda) doesn't recognize .py.in files during import. For example, import pdb2pqr fails to find pdb2pqr.py.in.

Do I need to switch python versions, or is there another workaround?

**Comment by kozlac** [comment]
Hello @mjag1898, It sounds that you have the source files for pdb2pqr. In order to install and run PDB2PQR please follow [these instructions](https://github.com/Electrostatics/apbs-pdb2pqr/blob/master/pdb2pqr/INSTALL.md). Once you configure and run the scons and scons install you should have a pdb2pqr.py file in the selected installation folder. 

If you need further help, please let me know. Thanks!!
