### ISSUE TITLE
Bug in psize.py?

### ISSUE THREAD

**Issue by Jerkwin** [Electrostatics/apbs-pdb2pqr#525]
In `apbs-pdb2pqr/apbs/tools/manip/psize.py`, line 166

```python
		zofac = 1 + 2 * self.constants["ofrac"]
		for i in range(3):
			self.np[i] = n[i]/float(nsmall[i])
166			if self.np[i] > 1: self.np[i] = int(zofac*n[1]/nsmall[i] + 1.0)
		return self.np
```

Should `n[1]/nsmall[i]` be `n[i]/nsmall[i]` ? Otherwise, I can't understand the logic.

**Comment by sobolevnrm** [comment]
Hello--

This does look like a bug.  I'll check with others on the development team for a fix.

Thank you,

Nathan
________________________________

**Comment by Jerkwin** [comment]
Hi Nathan,

Any responses from the development team? I would like to make sure this is indeed a bug.

Thanks,
Jicun

**Comment by sobolevnrm** [comment]
Hello –

I apologize that I have not.  I will Cc them again.

Thank you,

Nathan

**Comment by Eo300** [comment]
I went and patched a fix for this in the most recent commit f83c140.  Both psize.py files in the [apbs/tools/manip ](https://github.com/Electrostatics/apbs-pdb2pqr/tree/master/apbs/tools/manip) and [pdb2pqr/src](https://github.com/Electrostatics/apbs-pdb2pqr/tree/master/pdb2pqr/src) directories should now be reflected to use the index ```i```  instead of ```1```

**Comment by sobolevnrm** [comment]
Jicun, we have made the change. Thanks for finding the error.

Sent from my iPhone

On Aug 9, 2019, at 3:56 PM, Nathan Baker <nathanandrewbaker@gmail.com<mailto:nathanandrewbaker@gmail.com>> wrote:

Hello –

I apologize that I have not.  I will Cc them again.

Thank you,

Nathan

**Comment by Jerkwin** [comment]
Thanks for the fix.
