### ISSUE TITLE
Large apbs .dx file downloads fail from web server due to server-side error?

### ISSUE THREAD

**Issue by sherif10002** [Electrostatics/apbs-pdb2pqr#595]

**Comment by sobolevnrm** [comment]
@Eo300 can you please investigate this problem?

**Comment by sobolevnrm** [comment]
Perhaps a temporary fix would be to compress files on server side?

**Comment by Eo300** [comment]
From investigating the issue it seems that there's a worker timeout occurring on the server-side storage service.  I can lift it to an extent, but ultimate a slow-enough download speed would still experience the same issue.

Regarding compressing files server-side, I can apply that, since it should alleviate some of these troubles in terms of sheer file size.

**Comment by sherif10002** [comment]
Compressing the files sounds like a great solution

**Comment by stefanhuber1993** [comment]
My current workaround is to download the file via commandline and ```wget```. Download seems to continue upon reconnect.

**Comment by sherif10002** [comment]
Thank you @stefanhuber1993 this worked.

**Comment by Eo300** [comment]
Happy to see that's working for now.  As for compressing the files server-side, that's now implemented, so future submissions should show the resulting `.dx` file as `.dx.gz`.

**Comment by sobolevnrm** [comment]
Thanks for the quick turnaround on this, @Eo300 !  Something for a discussion offline:  did you increment version numbers, etc.?
